### ISSUE TITLE
Docstring causes tooltip crash

### ISSUE THREAD

**Issue by schodge** [DamnWidget/anaconda#335] opened 2015-06-03 21:55 UTC
In a function, I have the following docstring:

    """With help from
    http://stackoverflow.com/questions/9321741/printing-to-screen-and-writing-to-a-file-at-the-same-time
    """

If I do something - e.g., type in the name of the function - that would cause the tool tip to bring this docstring up, Sublime crashes / closes.  If I remove the docstring, there's not a problem.  Overly long URL causing a problem?

**Comment by DamnWidget** [comment] 2015-06-04 01:09
This looks like a ST bug itself, did you look for it in the ST bugs report
github repo?

**Comment by schodge** [comment] 2015-06-04 01:11
I looked around, didn't see it mentioned. Is there a crash log created
somewhere?

**Comment by DamnWidget** [comment] 2015-06-04 08:49
I couldn't find any information about crash logs locations for ST3 but seems like this is an unknown ST3 issue, [a search for the tooltip](https://github.com/SublimeTextIssues/Core/search?q=tooltip&type=Issues&utf8=%E2%9C%93) word in the reports site doesn't show anything similar.

I've tested this in a Linux box and I could reproduce it.

**Comment by schodge** [comment] 2015-06-04 22:53
Posted over in the Sublime Issues area.  https://github.com/SublimeTextIssues/Core/issues/879  Thanks for replicating.

**Comment by DamnWidget** [comment] 2016-05-11 20:26
Closing this as it will be fixed in next ST3 reelase -> https://github.com/SublimeTextIssues/Core/issues/1126#issuecomment-217270776

**Closed by DamnWidget** 2016-05-11 20:26 UTC
Labels: ST3 bug
