### ISSUE TITLE
Anaconda slow on long file, vanilla Sublime Text 3 on OSX

### ISSUE THREAD

**Issue by mrvkino** [DamnWidget/anaconda#558] opened 2016-10-12 19:11 UTC
With a vanilla install of Sublime Text 3 (3126) on OSX El Capitan (package control and anaconda only) my autocomplete gets slower with longer file.

With a file of 200 lines I have a delay between the time I type "print" and the autocomplete suggestion of 0.5-1s. With a file of 1600 lines it goes to 8 sec. The rate of delay is about 1 s for each 200 lines.

I tried following the debug procedure in the setting file but I got an error:

```
⋊> python -B anaconda_server/jsonserver.py -p test 9999 DEBUG
Usage: jsonserver.py -p <project> -e <extra_paths> ST3_PID

jsonserver.py: error: you have to pass a Sublime Text 3 PID
```

This is what I get for a file of 1600 lines. The file is on my computer.
![anaconda](https://cloud.githubusercontent.com/assets/279511/19324097/d7aa3a1a-908d-11e6-99e7-3e926b8262ec.gif)

**Comment by DamnWidget** [comment] 2016-10-12 19:37
I don't think is because how many lines the file has, probably your JsonServer is crashing and restarting in a loop. To enable the debug mode you just need to remove the port in the command that you pasted above, the port is not needed anymore in POSIX platform.

Start it in debug mode and let's take a look at the log

**Comment by mrvkino** [comment] 2016-10-12 20:17
I started the JsonServer

```
⋊> python -B anaconda_server/jsonserver.py -p test DEBUG
DEBUG:root:bind: address=/Users/Shadow/Library/Application Support/Anaconda/test/anaconda.sock
DEBUG:root:listen: backlog=5
INFO:root:Anaconda Server started in /Users/Shadow/Library/Application Support/Anaconda/test/anaconda.sock for PID DEBUG with cache dir /Users/Shadow/Library/Caches/Jedi/test
INFO:root:Anaconda Server started in DEBUG mode...
DEBUG MODE
```

When I open Sublime Text a pop-up tells me that it was not able to connect to the socket.

The socket mentioned exist and is under my username. If I use the command in Sublime Text console to test the socket, I get this message

```
>>> import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect('/Users/Shadow/Library/Application Support/Anaconda/hardent_tools/anaconda.sock')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: getsockaddrarg: AF_INET address must be tuple, not str
```

**Comment by DamnWidget** [comment] 2016-10-12 20:44
Ok, let's me explain you roughly how anaconda works.

When you open a folder or a project in your Sublime Text 3 in a window, anaconda assign an unique project name to that window, being this:
1. The project name itself is a project exists
2. The first opened directory in the Windows if a project is not set
3. The string "anaconda-" followed by the ID of the ST3 window if there are no open directory

Then, the anaconda's worker starts a JsonServer using the name that we detected in the previous step as value for the `-p` parameter, as you are in OS X, the JsonSever creates a new UNIX socket in `~/Library/Application\ Support/Anaconda/<project_name>/anaconda.sock`

That means that the value used for the parameter `-p` needs to match with the project or directory that you are gonna try to test. So in your case, you have to change the `-p test` to `-p hardent_tools`.

Make sure that you start the JsonServer while ST3 is completely closed (Cmd+Q)

**Comment by mrvkino** [comment] 2016-10-12 20:53
Ok, I got it working.

You can skip the linting error. I don't have my warning exclusion active in this vanilla install. At the end of the log there is a lot of unsuccessful attempt reported for the autocompletion of print.

[anaconda.txt](https://github.com/DamnWidget/anaconda/files/525620/anaconda.txt)

**Comment by DamnWidget** [comment] 2016-10-12 20:57
Is not the autocompletion, it is the signatures tooltips requesting the documentation of the symbol under the cursor.

Which Python version is that?
ST3 and Anaconda versions as well?

**Comment by mrvkino** [comment] 2016-10-12 21:01
I have python 3.4.2 under pyenv. Sublime text is 3126. Anacaonda is 2.1.1

**Comment by DamnWidget** [comment] 2016-10-12 21:09
There should be something environmental going on here, I just created a file with 8000 lines just duplicating the same code, the linting was a bit slower but the tooltips and completions where as fast as always (the whole package is design to make it fast in that specific scenario).

Can you try to use another Python interpreter that is not under pyenv please?

**Comment by mrvkino** [comment] 2016-10-12 22:43
I have set the python interpreter to /usr/bin/python (which is the system python of OSX) and I get the same behavior.

[anaconda.txt](https://github.com/DamnWidget/anaconda/files/525786/anaconda.txt)

**Comment by DamnWidget** [comment] 2016-10-13 08:11
The logs looks pretty normal to me, you can try to disable the use of docstrings for the tooltips, set this `enable_docstrings_tooltip` to `false` in your config, if it doesn't help you can try to disable the display of signatures all together setting `display_signatures` to `false` and see if there is any kind of improvement.

**Comment by mrvkino** [comment] 2016-10-13 13:02
If I put the ```display_signatures``` to ```false``` it speeds it up a lot. I would really like to get the signature back especially for function or classes I don't use a lot.

```enable_decstrings_tooltip``` doesn't seem to change anything much.

**Comment by DamnWidget** [comment] 2016-10-13 14:26
I am pretty sure that the jsonserver is crashing when the signatures is enabled, is the only thing that could explain the delay, it's hard to try to debug a problem that is not happening to you just using this issues tracker list...

**Comment by mrvkino** [comment] 2016-10-13 14:41
I could always try to do more in-depth debug on my side to get you more information. I would just need some pointers on where to start.

**Comment by mrvkino** [comment] 2016-10-13 17:45
I did a little digging in the tagged version of Anaconda in github. I used my default pyenv python 3.4 setup. With my current vanilla setup and Anaconda set to 1.4.28 the popup is instantaneous with all tooltips enable. Starting with 2.0.0, I start getting the slowdowns.

I don't know if this narrows it down, since it is at the time of the major rewrite of Anaconda.

**Comment by DamnWidget** [comment] 2016-10-13 17:59
Not much really, if you are not using docker, vagrant or remote interpreters is probably fine if you use 1.4.28 anyway, I think if you start the jsonserver manually in debug mode and set the `jsonserver_debug` as `true` you will find crash reports in your terminal after a few minutes of use.

Note: if you enable the `jsonserver_debug` anaconda will not try to start a jsonserver by itself ever, remmeber to set it as `false` when you stop your manually started jsonserver.

**Comment by karolyi** [comment] 2016-12-09 20:16
I experience the same slowdown since a recent anaconda update. Can I help out somehow here?

**Comment by Chovin** [comment] 2016-12-12 00:44
am also seeing this

**Comment by DamnWidget** [comment] 2016-12-12 11:16
Hi guys,
Can you please provide your JsonServer logs with the timeframe that you experience the slow down?

**Comment by DamnWidget** [comment] 2016-12-14 17:33
Hi guys,
Can you please provide your JsonServer logs with the timeframe that you experience the slow down?

**Comment by adrn** [comment] 2016-12-20 16:51
FWIW, I think #532 is actually the same issue as what is discussed here. I'm still seeing this. Will try getting a jsonserver log

**Comment by mrvkino** [comment] 2017-01-29 22:35
I have a new log. I have a project with file under 300 lines each and Anaconda is blazing fast. I tested the pdb.py file from python 3.4 in my project and tried anaconda on it. It is better than before, but there is still a clear lag on the suggestion/documentation.

I did the following test:
I tried anaconda on my project files for a couple seconds and every command such as "re." and "print". Everything popped the list of completion immediately. Then I opened the pdb.py file and when I typed "re." the suggestion list took about 2-3 seconds to pop, the same thing happened for "print". The argument autocomplete of print took 2-3 second to execute. It executed while I was typing argument and completed the argument in the middle of my text (creating a mess of my argument value and anaconda default autocompletion).

It seems the slowdown happens when we are working in a big file. If I import pdb in one of my short script, the autocomplete runs fine when completing pdb and listing the available function.

[anaconda_jsonserver.txt](https://github.com/DamnWidget/anaconda/files/737851/anaconda_jsonserver.txt)

**Comment by DamnWidget** [comment] 2017-01-29 23:25
Can you try to disable pep257 and try again?

**Comment by mrvkino** [comment] 2017-01-30 02:41
I did not see much change in the speed of the behaviour on "pdb.py".

[anaconda_jsonserver.txt](https://github.com/DamnWidget/anaconda/files/738053/anaconda_jsonserver.txt)

**Comment by DamnWidget** [comment] 2017-01-30 09:52
I do not really see many delay in your logs, for example:
```017-01-29 21:38:58,435: INFO    : client requests: lint
2017-01-29 21:38:58,816: INFO    : About push back to ST3: b'{"errors": [{"raw_error": "[W] PEP 8 (E305):....
```
Or 
```
2017-01-29 21:39:28,935: INFO    : client requests: autocomplete
2017-01-29 21:39:28,955: INFO    : About push back to ST3: b'{"completions": [["raise\\tkeyword", "raise"],
```
As you can see the times looks fine, is just at the end of your previous report that times increase a bit, always under a second, except for the linter (pep257 is pretty expensive by the way).

I am not able to reproduce this behavior, in my case linting is a bit slow, `self` introspection is slower than standard library but that is expected. Here a video editing `pdb.py`

![pdb_py_behavior](https://cloud.githubusercontent.com/assets/329766/22418634/b4ccf2cc-e6d1-11e6-96ad-e09813d4d06d.gif)

**Comment by Cescfangs** [comment] 2017-02-11 06:40
same here

**Comment by DamnWidget** [comment] 2017-02-11 12:45
hey @Cescfangs try to disable MyPy in your settings or just install MyPy for the same Python interpreter that you are using with anaconda.

**Comment by mrvkino** [comment] 2017-02-22 16:37
I might have a better input in what might be happening. I recorded the log while I was typing. The slowdown seems to be in the back and forth when typing.

In the first file "Untitled.py" I have 1076 line of comment with slash in them (nothing else). When I type the "import" keyword it seems to send some data every second after finishing typing.

If I go for an empty file it works instantly. It does the same thing but in less than a second.

I got the same behaviour with a vanilla Sublime Text 3 setup.

BTW: I reduced the frame rate (30 to 10) so the gif could be small enough.

![out](https://cloud.githubusercontent.com/assets/279511/23220604/84509140-f8f0-11e6-8e15-71fe5e8092c2.gif)

**Comment by oscarbranson** [comment] 2017-03-02 23:17
Hi Folks.

Also having this problem. It's becoming quite an irritation, as I keep working despite the delay, and then Anaconda attempts all kinds of edits/autocompletes all at once when I pause, and can introduce some crazy garbage into my code...

ST 3126
Anaconda 2.1.14
Python 3.5.2

Delay is highly variable - anywhere from 1 second to ~10 seconds (i.e. related to phase of json server restart loop?)

Any suggestions welcome!

**Comment by AndreasBackx** [comment] 2017-03-04 20:01
i'm experiencing some significant slowdowns in larger files. Here are the logs from one of those big files when having the following code in there somewhere

```python
import os
os
```

For the big file the logs start as soon as I go to the editor and press `.` on my keyboard and wait for Anaconda to update the autocomplete. It ranges from 3 to about 7 seconds sometimes depending on what it tries to autocomplete. The example here takes about 5 seconds to complete in the large file (1400 lines) and is instant on a file where the given code is the only code in the file.

[Logs from large file](https://hastebin.com/abeyateric.js)
[Logs from small file](https://hastebin.com/obalowales.js)

I hope these log files are somewhat useful to you.

**Comment by DamnWidget** [comment] 2017-03-16 13:25
Hi there guys. I've been finally able to deterministically reproduce this problem in my macOS 10.11.6 so I am currently in a good position to try to solve the issue. I am closing this issue as #620 is a duplicated of this one. 

Let's follow up in the other one.

**Closed by DamnWidget** 2017-03-16 13:25 UTC
