### ISSUE TITLE
Autocomplete, Docstring, GotoDefinition are very slow

### ISSUE THREAD

**Issue by easton402** [DamnWidget/anaconda#620] opened 2017-02-28 01:57 UTC
## Expected Behaviour
Autocomplete, Docstring, GotoDefinition should appear immediately after triggered.

## Actual Behaviour
Autocomplete, Docstring, GotoDefinition pop up several seconds later after triggered.

## Steps to Reproduce
[Reproduce_Sample.py.txt](https://github.com/DamnWidget/anaconda/files/805524/Reproduce_Sample.py.txt)
Open attached file, place cursor at the end, press CTRL + ALT + D or type '(' to trigger Docstring, or CTRL + ALT + G to trigger go_to_defination, or import new modules.

## ST3, Anaconda and OS versions
ST3: Build 3126
Anaconda: commit 514456a7d5d17a292c53f95467778da9ae6c34f2 (Feb 23, 2017)
OS version: macOS Sierra 10.12.3 (16D32)
Python: on both Python 2.7.10 and Python 3.6.0

## ST3 Console Logs
No log.

## Anaconda's JsonServer Logs
Normal.

**Comment by easton402** [comment] 2017-03-02 18:48
```
from Anaconda.anaconda_lib.workers.market import Market
print(Market.get(Market, window.id()).interpreter)
```
gives result:`/usr/local/bin/python -B /Users/easton/Library/Application Support/Sublime Text 3/Packages/anaconda/anaconda_server/jsonserver.py -p anaconda-2 9311`, I set Python2.7.10 as the interpreter (I tried Python3.6.0, which also suffered from the lag)

I dug a little, I set `jsonserver_debug` to `true`, and used the above result to launch jsonserver, and observed the jsonserver log when I was typing. I found jsonserver returned docstring result 2 seconds behind my typing, and the docstring displayed 2 seconds behind jsonserver returned. I can't figure out where the lag is.

Attached is the recording, 72 seconds, a little bit long.
![2017-03-02 10_26_47](https://cloud.githubusercontent.com/assets/10185801/23521593/7f44fa20-ff34-11e6-8906-01e1d516cf79.gif)

**Comment by easton402** [comment] 2017-03-02 19:18
My speculation is that not jsonserver causes the lag, but the plugin itself, maybe it has performance flaw when processing too long view.
Let me know if I'm wrong.

**Comment by easton402** [comment] 2017-03-02 19:24
I also tried removing all other plugins and only left Anaconda and Package Control, this issue remained.

**Comment by DamnWidget** [comment] 2017-03-02 19:47
If the plugin had any kind of performance problem it should appear in all the platforms, there is some other macOS users with performance problems, all of them since Sierra update if I am not mistaken. I do not believe in coincidences probably there is something that is affecting ST3 itself, or making the `socket` module of the ST3 embedded interpreter to misbehave.

I have been never able to reproduce it by  myself on any of my boxes (I use OSX El Capitan and I am notr planing to update it to Sierra any time soon). To properly investigate this I must be able to reproduce it or wotk with someone that has the problem and have the time and the motivation to try to go deeper until we can find the cause of the problem and find a solution.

**Comment by DamnWidget** [comment] 2017-03-16 13:22
I could reproduce it with the sample file in macOS without update to Sierra. I will take a deeper look into it to try to find the cause of the problem and provide a satisfactory solution.

Please let's maintain just a single ticket for this issue, I will proceed to close #558 so we can follow up the issue in this one.

**Comment by DamnWidget** [comment] 2017-03-16 14:15
This issue has been resolved and it's fix will be released later today

Note: do not use UNIX Domain Sockets in macOS, seriously, don't

**Comment by easton402** [comment] 2017-03-16 16:31
This is awesome, @DamnWidget well done.

**Comment by DamnWidget** [comment] 2017-03-16 21:43
This issue must be fixed as per release v2.116 

Sorry to all macOS users for the delay but just reproduce and understand the issue was a really long task and I am a very busy person.

Feel free to re-open if you find any more related problems (that I hope you don't)

**Closed by DamnWidget** 2017-03-16 21:43 UTC
Labels: resolved

**Comment by loricheung** [comment] 2018-02-07 07:38
Hi, I use anaconda v2.1.25, sublime text3 build 3143 and high sierra
And I am confusing about anaconda lint, for example I imported a package named pandas, then i typed "pandas.", it will take a long time to show the lint, in my case, it was 23 seconds!
  
here is the jsonserver log file 
[anaconda_jsonserver.log](https://github.com/DamnWidget/anaconda/files/1702135/anaconda_jsonserver.log)

watch the line in 2018-02-07 15:16:13 and the next line

**Comment by DamnWidget** [comment] 2018-02-07 08:48
What you are describing is the autocompletion and not the linting, anyway, that is normal when you the plugin loads an huge module as `pandas` for the first time as it has to analyze it and cache it, but that is just the first time that it gets loaded, after that everythign must come from the cache.

**Comment by loricheung** [comment] 2018-02-07 08:58
thanks, so it is !  well here is from china and my english is not so good :)
now I have more resons to stay with sublime text instead of pycharm
