### ISSUE TITLE
exception constantly happening after upgrade: initial check failed

### ISSUE THREAD

**Issue by franklingu** [DamnWidget/anaconda#526] opened 2016-09-01 10:43 UTC
~~~
<Anaconda.anaconda_lib.workers.local_worker.LocalWorker object at 0x7f0986c3f350> initial check failed because:

can not connect to /home/jgu/.local/share/anaconda/run/dat/anaconda.sock

check that there is Python process executing the anaconda jsonserver.py script running in your system. If there is, check that the Unix Domain Socket file /home/jgu/.local/share/anaconda/run/dat_web/anaconda.sock exists and that you can connect to it writing the following script in your Sublime Text 3 console:

import socket; socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect(/home/jgu/.local/share/anaconda/run/dat_web/anaconda.sock)
~~~

1. I am getting this error
2. there is error in the code snippet, it should be:
~~~
import socket; socket.socket(socket.AF_UNIX, socket.SOCK_STREAM).connect('/home/jgu/.local/share/anaconda/run/dat_web/anaconda.sock')
~~~
and for me there is no exception or anything

**Comment by DamnWidget** [comment] 2016-09-01 11:21
You are not using latest version, update to v2.0.6 and try again (paste the output if you get the same error)

**Comment by DamnWidget** [comment] 2016-09-01 13:22
Duplicate of #514

**Closed** 2016-09-10 12:28 UTC
Labels: duplicate
