### ISSUE TITLE
Anaconda can not spawn a new process with your current configured python interpreter

### ISSUE THREAD

**Issue by felyxjet** [DamnWidget/anaconda#314] opened 2015-05-04 16:55 UTC
Since recently i get "Anaconda can not spawn a new process with your current configured python interpreter (C:\Python27\python.exe), make sure your interpreter is a valid binary and is in your PATH or use an absolute route to it, for example: C:\Python27\python.exe" error messages all the time. 

OS: Windows 7 64-bit
Python version: Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Python specific settings:
```
{
	"python_interpreter": "C:\\Python27\\python.exe",
}
```
Sublime log:
ERROR:root:Your operating system denied the spawn of C:\Python27\python.exe process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
...

**Comment by cryzed** [comment] 2015-05-05 21:27
You want to use double slashes to escape a single slash properly in JSON. It should look like this: ```"C:\\Python27\\python.exe"```.

**Comment by DamnWidget** [comment] 2015-05-07 08:50
Can you open the interpreter from the command line tool (CMD.exe) using that same path?

**Comment by felyxjet** [comment] 2015-05-07 08:57
Yep

**Comment by kissgyorgy** [comment] 2015-05-10 10:34
I have this same issue on OS X 10.9 and I had to uninstall Anaconda, because it became unusable with this bug :(

**Comment by DamnWidget** [comment] 2015-05-10 12:47
Well, the only way that I've been able to reproduce this is just writing the wrong path to the Python interpreter in the settings. I can't reproduce that problem using correct paths so please, review you wrote the right path and the user executing ST3 has permissions to execute the python interpreter in the configured path.

**Comment by felyxjet** [comment] 2015-05-10 13:30
Path is absolutely correct, you can tell that even by error msg ""Anaconda can not spawn a new process with your current configured python interpreter (```C:\Python27\python.exe```), make sure your interpreter is a valid binary and is in your PATH or use an absolute route to it, for example: ```C:\Python27\python.exe```"". At least i don't see any issues with it. So, i guess the problem with that another reason you mentioned. How exactlt do i verify that a user executing ST3 has permissions to execute the python interpreter in the configured path?

**Comment by DamnWidget** [comment] 2015-05-10 13:37
Hi. You can try to change the code of the anaconda's process spawner to give you detailed information about what the problem exactly is.

If you open [this file](https://github.com/DamnWidget/anaconda/blob/6e56862bba3a8acf9a9df9038b941fe3c429468b/anaconda_lib/helpers.py#L126) in the `anaconda_lib` directory you can change the code below to something like:

```python
except Exception as err:
        logging.error(
            'Your operating system denied the spawn of {}'
            ' process. Make sure your configured interpreter is a valid python'
            ' binary executable and is in the PATH'.format(args[0])
        )
        logging.error('The underlying error is: {}'.format(err))
```

**Comment by felyxjet** [comment] 2015-05-10 13:45
```[WinError 267] The directory name is invalid```

**Comment by DamnWidget** [comment] 2015-05-10 13:54
I just found this O.o https://support.microsoft.com/en-us/kb/832434

Not sure what is causing that but the only available answers are:

1) The ST3 python interpreter is building a wrong Windows path like C:\\Python32/python.exe (instead of C:\\Python32\\Python.exe) that I doubt as the path is just fine in the message
2) Some windows crazyness

Not sure how can I help you here.

**Comment by felyxjet** [comment] 2015-05-10 14:01
Let me help you. I added some more output and here's what i've got:
```
ERROR:root:Your operating system denied the spawn of C:\Python27\python.exe process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
ERROR:root:The underlying error is: [WinError 267] Неверно задано имя папки
ERROR:root:PATH: C:\Users\felyxjet\Desktop\login_logout_signup
ERROR:root:ARGS: ['C:\\Python27\\python.exe', '-B', 'C:\\Users\\felyxjet\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_lib\\../anaconda_server\\jsonserver.py', '-p', 'login_logout_signup', '57439', '-e', 'C:\\Users\\felyxjet\\Desktop\\login_logout_signup', '15548']
ERROR:root:KWARGS: {'cwd': 'C:\\Users\\felyxjet\\Desktop\\login_logout_signup', 'startupinfo': <subprocess.STARTUPINFO object at 0x0000000003BF5358>, 'bufsize': -1}
```
The problem with that login_logout_signup folder. I doesn't exists anymore. I used to have a project on Desktop named login_logout_signup but i deleted it. I guess about since then i started getting that errors. This looks similar to this https://github.com/divmain/GitSavvy/commit/3098732961bc669a380011633935f9ed4600679c

**Comment by DamnWidget** [comment] 2015-05-10 14:08
From where that login_logout_signup directory is coming? Is in your configuration?

**Comment by DamnWidget** [comment] 2015-05-10 14:13
I will take a look into this tomorrow (I gotta go today) but I need to understand first from where that directory is coming, please, try to find from where this cwd is coming as it should be elsewhere in your configuration or environment.

**Comment by felyxjet** [comment] 2015-05-10 14:18
Yep. Nvm, i fixed that myself already. Just removed all entrances with that folder from Session.sublime_session and error is gone. So, either ST glitch or just me fucked it up somehow. @kissgyorgy try the same with ~/Library/Application Support/Sublime Text 3/Settings/Session.sublime_session.

**Comment by kissgyorgy** [comment] 2015-05-10 15:03
Based on your recommendations, I gave it a try.
I'm not sure what was wrong with my case, but I removed and reinstalled every affected virtualenv, uninstalled anaconda, deleted every Anaconda-related settings and cache files from Sublime folder, restarted, removed and reinitialized settings and it's working now! :+1: 
Awesome plugin BTW!

**Comment by felyxjet** [comment] 2015-05-10 15:09
@kissgyorgy oh, i only now realized your case is different from mine :smile: glad you also figured it out

**Comment by DamnWidget** [comment] 2015-05-11 14:00
Seems like new versions of Sublime Text 3 maintain rubbish in the cache and that is affecting anaconda's project code auto-referencing in some way in some specific scenarios I will take a look on that as soon as I have some time.

**Comment by DamnWidget** [comment] 2015-05-12 10:52
I released a new version that hopefully solves this problem. 
Feedback?

**Comment by felyxjet** [comment] 2015-05-12 18:06
@DamnWidget well, except that one time when i tried i don't create projects in ST anymore. After fixing Session.sublime_session Anaconda works damn good so far.

**Comment by DamnWidget** [comment] 2015-05-13 08:54
Happy to hear that

**Comment by lawlietfans** [comment] 2015-05-17 13:29
@felyxjet in my Windows 64bit, ` session.sublime_session` is in `C:\Users\von\AppData\Roaming\Sublime Text 3\Local` .  in my case, only empty this file is useless.   
when i uninstall Anaconda and reinstall it , the plug worked properly

**Comment by bofm** [comment] 2015-05-25 19:44
*How to solve this error?*
1) remove all non-existent directories from current ST project
2) it it doesn't help, keep looking into :)

**Comment by lawlietfans** [comment] 2015-05-26 12:20
@bofm  maybe you can try the following step：
1.  empty `session.sublime_session`  
>on windows platforms, the file in this folder: `C:\Users\youraccount\AppData\Roaming\Sublime Text 3\Local` 
2.  uninstall this plugins and reinstall it.
3.  it should be ok,   and   you can edit `Pakage Settints`->`Anaconda`->`Settings-User`
```py
{
//in theory, if you add python Application path to Windows environment variable PATH, `python_interpreter` is undesired
    "python_interpreter": "D:\\Program Files\\Python34\\python.exe",  // input your python interpreter path
    "auto_python_builder_enabled": false,
}
```

**Comment by fgimian** [comment] 2015-06-03 06:05
Same issues here folks, Windows 8.1 with Python 2.7.  My python interpreter is in the PATH and definitely runs fine.  I've also tried overriding the python_interpreter setting with the absolute path but no joy.

**Comment by felyxjet** [comment] 2015-06-03 19:25
@fgimian make [this file](https://github.com/DamnWidget/anaconda/blob/6e56862bba3a8acf9a9df9038b941fe3c429468b/anaconda_lib/helpers.py#L124 ) to look like this:
```python
    try:
        return subprocess.Popen(args, **kwargs)
    except Exception as e:        
        logging.error(
            'Your operating system denied the spawn of {}'
            ' process. Make sure your configured interpreter is a valid python'
            ' binary executable and is in the PATH'.format(args[0])
        )
        logging.error(e)
        logging.error('PATH: ' + os.path.dirname(__file__))
        logging.error('ARGS: ' + str(args))
        logging.error('KWARGS: ' + str(kwargs))
```

Then open ST console and check what's going on.

**Comment by fgimian** [comment] 2015-06-03 22:04
Thanks a lot, here we go :smile: 

```
ERROR:root:Your operating system denied the spawn of C:\Development\Python27\python.exe process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
ERROR:root:[WinError 267] The directory name is invalid
ERROR:root:PATH: C:\Users\Fots\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib
ERROR:root:ARGS: ['C:\\Development\\Python27\\python.exe', '-B', 'C:\\Users\\Fots\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_lib\\../anaconda_server\\jsonserver.py', '-p', 'easysnmp', '3814', '-e', '', '5160']
ERROR:root:KWARGS: {'cwd': 'Z:\\easysnmp', 'bufsize': -1, 'startupinfo': <subprocess.STARTUPINFO object at 0x000000DD16A5FCF8>}
ERROR:root:Your operating system denied the spawn of C:\Development\Python27\python.exe process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
ERROR:root:[WinError 267] The directory name is invalid
ERROR:root:PATH: C:\Users\Fots\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib
ERROR:root:ARGS: ['C:\\Development\\Python27\\python.exe', '-B', 'C:\\Users\\Fots\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_lib\\../anaconda_server\\jsonserver.py', '-p', 'easysnmp', '3814', '-e', '', '5160']
ERROR:root:KWARGS: {'cwd': 'Z:\\easysnmp', 'bufsize': -1, 'startupinfo': <subprocess.STARTUPINFO object at 0x000000DD16A5FDD8>}
error: Anaconda can not spawn a new process with your current configured python interpreter (C:\Development\Python27\python.exe), make sure your interpreter is a valid binary and is in your PATH or use an absolute route to it, for example: C:\Python27\python.exe
ERROR:root:Your operating system denied the spawn of C:\Development\Python27\python.exe process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
ERROR:root:[WinError 267] The directory name is invalid
ERROR:root:PATH: C:\Users\Fots\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib
ERROR:root:ARGS: ['C:\\Development\\Python27\\python.exe', '-B', 'C:\\Users\\Fots\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_lib\\../anaconda_server\\jsonserver.py', '-p', 'easysnmp', '3814', '-e', '', '5160']
ERROR:root:KWARGS: {'cwd': 'Z:\\easysnmp', 'bufsize': -1, 'startupinfo': <subprocess.STARTUPINFO object at 0x000000DD16A5FF98>}
ERROR:root:Your operating system denied the spawn of C:\Development\Python27\python.exe process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
ERROR:root:[WinError 267] The directory name is invalid
ERROR:root:PATH: C:\Users\Fots\AppData\Roaming\Sublime Text 3\Packages\Anaconda\anaconda_lib
ERROR:root:ARGS: ['C:\\Development\\Python27\\python.exe', '-B', 'C:\\Users\\Fots\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_lib\\../anaconda_server\\jsonserver.py', '-p', 'easysnmp', '3814', '-e', '', '5160']
ERROR:root:KWARGS: {'cwd': 'Z:\\easysnmp', 'bufsize': -1, 'startupinfo': <subprocess.STARTUPINFO object at 0x000000DD16A794A8>}
```

I think the problem is here:

```
'C:\\Users\\Fots\\AppData\\Roaming\\Sublime Text 3\\Packages\\Anaconda\\anaconda_lib\\../anaconda_server\\jsonserver.py', '-p', 'easysnmp', '3814', '-e', '', '5160']
```

You should probably avoid using / in any of the code and rely on `os` instead for all these things :smile: 

e.g.

```python
@cache
def valid_languages(**kwargs):
    """Return back valid languages for anaconda plugins
    """

    path = os.path.join(os.path.dirname(__file__), '../../')
    languages = [
        f.rsplit('_', 1)[1].lower() for f in os.listdir(path)
        if f.startswith('anaconda_') and 'vagrant' not in f
    ]

    return ['python'] + languages
```

You can change:

```python
    path = os.path.join(os.path.dirname(__file__), '../../')
```

to

```python
    path = os.path.join(os.path.dirname(__file__), os.pardir, os.pardir)
```

I'll try it out now and let you know if that fixes my problem :smile:

**Comment by fgimian** [comment] 2015-06-03 22:08
No luck yet, but you'll also need to update this in `worker.py` (i should probably just put together a pull request, hehe):

```python
    def build_server(self):
        """Create the subprocess for the anaconda json server
        """

        script_file = os.path.join(
            os.path.dirname(__file__), os.pardir,
            'anaconda_server', 'jsonserver.py'
        )
...
```

**Comment by fgimian** [comment] 2015-06-03 22:17
Alrgihty, got it working.  The last problem was that I had a project open in my browser which no longer existed.  This seems to trip up anaconda.

To fix this, you'll need to update the following in worker.py:

```python
        kwargs = {}
        if (
            len(sublime.active_window().folders()) > 0 and
            os.path.exists(sublime.active_window().folders())
        ):
            kwargs['cwd'] = sublime.active_window().folders()[0]
```

And now I have a fully working anaconda :smile: 

Please let me know if you would like to roll this up into a pull request for you.  Happy for you to just incorporate the fixes if you like.

Cheers
Fotis

**Comment by DamnWidget** [comment] 2015-06-04 01:08
I guys.
Please, make a pull request with any fix it will be included into the next
release.

**Comment by fgimian** [comment] 2015-06-04 04:11
Okies, I've just fixed this now with a branch [windows-fixes](https://github.com/fgimian/anaconda/tree/windows-fixes).

I'll test this thoroughly when I get home but if others would like to give it a try too, that would be great.

Once confirmed all is well, I'll send it in as a pull request.
Fotis

**Comment by DamnWidget** [comment] 2015-06-04 08:59
It looks fine to me.

**Comment by fgimian** [comment] 2015-06-04 09:06
Awesome, I just got home and am about to test it and will then send over a pull request :smile:

**Comment by Pirou01** [comment] 2015-06-09 07:31
It also worked for me

Thanks

**Comment by ProProgrammer** [comment] 2015-07-05 18:45
Just observed this issue on Ubuntu 14.04.2 LTS
`"python_interpreter"` in `Preferences > Package Settings > Anaconda > Settings - Default` set to `"/usr/bin/python"`
I confirmed the changes from commit 66bfa39 are there in my anaconda plugin installation files.

I had fresh installed Anaconda plugin just a few hours back and till not it was working perfectly fine.
When I first faced this issue (about 15 mins back, I thought this was because `"python_interpreter"` was set to `"python"` hence I then changed it to `"/usr/bin/python"` but still the issue remains.

Environment: Ubuntu 14.04.2 LTS, Python 2.7.6, Sublime Text 3 Build 3083

**Comment by DamnWidget** [comment] 2015-07-06 08:53
Something in the ST3 console log?

**Comment by ProProgrammer** [comment] 2015-07-06 14:24
I had disabled the plugin, now I just re-enabled it with Console open, and I observed this in log:

`reloading plugin Anaconda.anaconda`
`reloading plugin Anaconda.version`
`generating meta info summary`
`reloading Packages/User/Preferences.sublime-settings`
`reloading Packages/User/Preferences.sublime-settings`
`ERROR:root:Your operating system denied the spawn of /usr/bin/python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH`

**Comment by DamnWidget** [comment] 2015-07-06 14:31
Open the ST3 console and write there:
import subprocess; subprocess.call(["python", "-c", "print('Hello world')"])

What's the output?

**Comment by ProProgrammer** [comment] 2015-07-06 14:35
Output was `0`

`>>> import subprocess; subprocess.call(["python", "-c", "print('Hello world')"])`
`0`

**Comment by DamnWidget** [comment] 2015-07-06 14:38
Sorry, I edit the comment after write it, try with `/usr/bin/python`

**Comment by ProProgrammer** [comment] 2015-07-06 14:41
Output is still exactly same

```python
>>> import subprocess; subprocess.call(["/usr/bin/python", "-c", "print('Hello world')"])
0
```

**Comment by DamnWidget** [comment] 2015-07-06 14:51
Try what I said in [this previous comment](https://github.com/DamnWidget/anaconda/issues/314#issuecomment-100642884) and come back with the result please.

**Comment by ProProgrammer** [comment] 2015-07-06 15:30
Thanks,
Here's the output:

```
ERROR:root:[Errno 111] Connection refused
ERROR:root:Traceback (most recent call last):
  File "/home/deep/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/worker.py", line 191, in start
    self.client = AsynClient(self.available_port)
  File "/home/deep/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/jsonclient.py", line 36, in __init__
    EventHandler.__init__(self, (host, port))
  File "/home/deep/.config/sublime-text-3/Packages/Anaconda/anaconda_lib/ioloop.py", line 107, in __init__
    self.sock.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
INFO:root:Registering handler with address ('localhost', 43296)
```

**Comment by DamnWidget** [comment] 2015-07-06 17:50
Then, I think that the question here is:
Why the `plugin_host` application can't connect to `localhost` in your system? It seems to be an environmental problem.

**Comment by ProProgrammer** [comment] 2015-07-07 00:58
Ok... Could you guide me through steps for solving this?? I have no idea how to troubleshoot and resolve sublime plugin issues.. Completely new to it.

**Comment by DamnWidget** [comment] 2015-07-07 08:46
Looking at the whole log file, seems like anaconda connect successfully in the second try `INFO:root:Registering handler with address ('localhost', 43296)` that means anaconda started a JsonServer with success in your machine.

Is not working properly now?

**Comment by eugenesvk** [comment] 2016-02-16 10:09
Hey, I have the same issue on OS X 10.11.3 with ST3 3103
I've added 
```
        logging.error(e)
        logging.error('PATH: ' + os.path.dirname(__file__))
        logging.error('ARGS: ' + str(args))
        logging.error('KWARGS: ' + str(kwargs))
```
to the `helpers.py` and here is the output 

```
[2016-02-16 12:56:18,245 - ERROR    - root] Your operating system denied the spawn of python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
[2016-02-16 12:56:18,246 - ERROR    - root] global name 'e' is not defined
[2016-02-16 12:56:18,248 - ERROR    - root] Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 135, in create_subprocess
    return subprocess.Popen(args, **kwargs)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
OSError: [Errno 63] File name too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 183, in start
    self.start_json_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 72, in start_json_server
    self.build_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 266, in build_server
    self.process = create_subprocess(args, **kwargs)
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 142, in create_subprocess
    logging.error(e)
NameError: global name 'e' is not defined
Emmet: No need to update PyV8
[2016-02-16 12:56:18,413 - ERROR    - root] Your operating system denied the spawn of python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
[2016-02-16 12:56:18,413 - ERROR    - root] global name 'e' is not defined
[2016-02-16 12:56:18,414 - ERROR    - root] Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 135, in create_subprocess
    return subprocess.Popen(args, **kwargs)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
OSError: [Errno 63] File name too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 183, in start
    self.start_json_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 72, in start_json_server
    self.build_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 266, in build_server
    self.process = create_subprocess(args, **kwargs)
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 142, in create_subprocess
    logging.error(e)
NameError: global name 'e' is not defined
[2016-02-16 12:56:18,431 - ERROR    - root] Your operating system denied the spawn of python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
[2016-02-16 12:56:18,431 - ERROR    - root] global name 'e' is not defined
[2016-02-16 12:56:18,432 - ERROR    - root] Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 135, in create_subprocess
    return subprocess.Popen(args, **kwargs)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
OSError: [Errno 63] File name too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 183, in start
    self.start_json_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 72, in start_json_server
    self.build_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 266, in build_server
    self.process = create_subprocess(args, **kwargs)
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 142, in create_subprocess
    logging.error(e)
NameError: global name 'e' is not defined
[2016-02-16 12:56:18,481 - ERROR    - root] Your operating system denied the spawn of python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
[2016-02-16 12:56:18,482 - ERROR    - root] global name 'e' is not defined
[2016-02-16 12:56:18,483 - ERROR    - root] Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 135, in create_subprocess
    return subprocess.Popen(args, **kwargs)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
OSError: [Errno 63] File name too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 183, in start
    self.start_json_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 72, in start_json_server
    self.build_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 266, in build_server
    self.process = create_subprocess(args, **kwargs)
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 142, in create_subprocess
    logging.error(e)
NameError: global name 'e' is not defined
reloading Packages/USERNAME/PackageSync.sublime-settings
Package Control: Installing 1 missing package
reloading Packages/USERNAME/Package Control.sublime-settings
reloading Packages/USERNAME/Preferences.sublime-settings
Package Control: The package "AutoHotkey" is either not available on this platform or for this version of Sublime Text
Package Control: Skipping automatic upgrade, last run at 2016-02-16 12:12:56, next run at 2016-02-18 12:12:56 or after
[2016-02-16 12:57:20,631 - ERROR    - root] Your operating system denied the spawn of python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
[2016-02-16 12:57:20,631 - ERROR    - root] global name 'e' is not defined
[2016-02-16 12:57:20,632 - ERROR    - root] Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 135, in create_subprocess
    return subprocess.Popen(args, **kwargs)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
OSError: [Errno 63] File name too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 183, in start
    self.start_json_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 72, in start_json_server
    self.build_server()
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/worker.py", line 266, in build_server
    self.process = create_subprocess(args, **kwargs)
  File "/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/helpers.py", line 142, in create_subprocess
    logging.error(e)
NameError: global name 'e' is not defined
```

Output of `>>> import subprocess; subprocess.call(["/usr/bin/python", "-c", "print('Hello world')"])` is `0`.
I have a `pyenv` (Homebrewed version), but python is set to system. Python is in the path and after invoking python from the terminal the same command gives out 
`Hello world
0`

**Comment by DamnWidget** [comment] 2016-02-16 10:23
What do you have in your `python_interpreter` configuration setting? The problem is that your OS X is complaining about a file name being too long when it tries to execute the Json Server as you can see in the log `OSError: [Errno 63] File name too long`

**Comment by felyxjet** [comment] 2016-02-16 10:37
@eugenesvk you forgot to add `except Exception as e:`

**Comment by eugenesvk** [comment] 2016-02-16 10:38
I have anything customized, so the default values are used.
I don't understand, which path OS X is complaining about. Is there a way to find this out?

**Comment by eugenesvk** [comment] 2016-02-16 10:42
@felyxjet thank you for pointing out the mistake. Added this exception and error log is as follows
```
[2016-02-16 13:41:19,014 - ERROR    - root] Your operating system denied the spawn of python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
[2016-02-16 13:41:19,015 - ERROR    - root] [Errno 63] File name too long
[2016-02-16 13:41:19,015 - ERROR    - root] PATH: /Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib
[2016-02-16 13:41:19,015 - ERROR    - root] ARGS: ['python', '-B', '/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py', '-p', 'anaconda-2', '60331', '57635']
[2016-02-16 13:41:19,016 - ERROR    - root] KWARGS: {'cwd': '/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib', 'bufsize': -1}
[2016-02-16 13:41:19,093 - ERROR    - root] Your operating system denied the spawn of python process. Make sure your configured interpreter is a valid python binary executable and is in the PATH
[2016-02-16 13:41:19,094 - ERROR    - root] [Errno 63] File name too long
[2016-02-16 13:41:19,094 - ERROR    - root] PATH: /Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib
[2016-02-16 13:41:19,094 - ERROR    - root] ARGS: ['python', '-B', '/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py', '-p', 'anaconda-2', '60331', '57635']
[2016-02-16 13:41:19,094 - ERROR    - root] KWARGS: {'cwd': '/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib', 'bufsize': -1}

```

**Comment by DamnWidget** [comment] 2016-02-16 11:27
What happens if you try to execute in your terminal the following?:
`python -B '/Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Anaconda/anaconda_lib/../anaconda_server/jsonserver.py'`

**Comment by eugenesvk** [comment] 2016-02-16 11:45
@DamnWidget 
I have the following error
```
Usage: jsonserver.py -p <project> -e <extra_paths> port

jsonserver.py: error: you have to pass a port number and PID
```
Tried to add `-p PROJECT 9999`, but it didn't work either. Not sure which parameters are correct for this server.

**Comment by eugenesvk** [comment] 2016-02-16 11:50
Btw, I've tried to use [ColorSublime](https://github.com/Colorsublime/Colorsublime-Plugin) plugin, which  I used long ago, and it also can't connect to the internet failing to find theme list.
I've noticed it also has the same `[Errno 63] File name too long`, which it didn't have before (a long while ago when I used it). So maybe something on my system is broken?

```
ERROR:Colorsublime.colorsublime.http:Unexpected exception: <class 'OSError'>
Traceback (most recent call last):
  File "colorsublime.http in /Users/USERNAME/Library/Application Support/Sublime Text 3/Installed Packages/Colorsublime.sublime-package", line 23, in _run_downloader
  File "colorsublime.http.downloaders.external in /Users/USERNAME/Library/Application Support/Sublime Text 3/Installed Packages/Colorsublime.sublime-package", line 25, in get
  File "./subprocess.py", line 576, in check_output
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
OSError: [Errno 63] File name too long
DEBUG:Colorsublime.colorsublime.io:Extracting archive to /Users/USERNAME/Library/Application Support/Sublime Text 3/Packages/Colorsublime - Themes/cache
ERROR:Colorsublime.colorsublime.async:Command execution error:
Traceback (most recent call last):
  File "colorsublime.async in /Users/USERNAME/Library/Application Support/Sublime Text 3/Installed Packages/Colorsublime.sublime-package", line 43, in cb
  File "colorsublime.lib.concurrent.futures._base in /Users/USERNAME/Library/Application Support/Sublime Text 3/Installed Packages/Colorsublime.sublime-package", line 397, in result
  File "colorsublime.lib.concurrent.futures._base in /Users/USERNAME/Library/Application Support/Sublime Text 3/Installed Packages/Colorsublime.sublime-package", line 356, in __get_result
  File "colorsublime.lib.concurrent.futures.thread in /Users/USERNAME/Library/Application Support/Sublime Text 3/Installed Packages/Colorsublime.sublime-package", line 72, in run
  File "colorsublime.commands in /Users/USERNAME/Library/Application Support/Sublime Text 3/Installed Packages/Colorsublime.sublime-package", line 30, in fetch_repo
  File "colorsublime.io in /Users/USERNAME/Library/Application Support/Sublime Text 3/Installed Packages/Colorsublime.sublime-package", line 23, in extract
  File "./tempfile.py", line 625, in write
TypeError: 'bool' does not support the buffer interface
ERROR:Colorsublime.colorsublime.status:Theme list not found. Please check internet connection or enable debug in settings and report the stack traces.
INFO:Colorsublime.colorsublime.status:ERROR: Theme list not found. Please check internet connection or enable debug in settings and report the stack traces
```

**Comment by DamnWidget** [comment] 2016-02-16 11:57
Well, I am not expert in OS X but yeah seems like something is worng. HFS+ file system (the default in OS X) limit for file names is 255 unicode character long, there is no limit for paths so you shouldn't get that error.

Take a look at what you have in your temp folders, maybe there is a very long named file in there, I will probably try to restart the system (did you try to turn it off and on again?) to see if the problem is recurrent.

**Comment by eugenesvk** [comment] 2016-02-16 12:13
Already restarted as soon as I found out the ColorSublime bug (thought it was system-specific). My temp folder (`/private/var/tmp`) has like 10 items with 200Kb, so doesn't seem to be a problem.

Is there a way to at least test which specific path it's complaining about? Quick google showed it might be an issue with the code itself not parsing links properly (e.g. using content of an xml file as input, giving out huge paths), but that's just outright speculation.
Any other hints are welcome.

**Comment by DamnWidget** [comment] 2016-02-16 13:16
Anaconda just uses whatever you have configures as `python_interpreter`, something is messing with how `subprocess.py` is working in your system/ST3 installation there is not much that I can do as I am not able to reproduce this error myself.

If I was you, I will create a simple Python script that made use of `subprocess.Popen` just to make an `ls -la` or something like that and try to execute it with your OS X system python installation, then you will probably discover if it's your OS X what is screwing things or it's the Python interpreter embedded into ST3 itself.

If it's ST3 itself I will suggest to complete uninstall and manually clear all the files in `Application Support` and reinstall it from scratch.

**Comment by eugenesvk** [comment] 2016-02-16 18:53
I found what the issue was! It relates to how ST3 reads shell environment details.
I have [Fish](fishshell.com) as my default shell and my `config.fish` had and `echo` command with some welcome message. And ST3 had that welcome message written in `PATH` variable.
So whenever `Anaconda` did its magic, it would trip over a long `PATH` (containing that lengthy welcome message without the typical `:` path separators) and give out that `OSError: [Errno 63] File name too long` error.
After I've moved the welcome message to its proper place in `fish_greeting.fish` function the error went away (and the other bug for ColorSublime also went away).

I found it out by chance when investigating why some addon wasn't able to read a shell environment variable for a GitHub API by running a `import os;os.environ` in ST3 console. While I still don't know how to make ST3 read environment variables from my shell config on start, at least I'm not worrying about this issue anymore.

**Comment by DamnWidget** [comment] 2016-02-16 20:07
If you wanna make your ST3 to read your environment variables you have to start it from a terminal using the `subl` command.

Closing this again :)

**Closed by DamnWidget** 2016-02-16 20:07 UTC

**Comment by Twizzledrizzle** [comment] 2016-05-30 08:23
With the previous Anaconda (python package) I had python_interpreter set to

`"C:/Anaconda2/python.exe"`

without any problems.

But with the latest Anaconda package I had to change python_interpreter to

`"C:/Anaconda2/pythonw.exe",`

I get the error that python27.dll is missing from my computer. It seems that I now only have a python27.pdb

Do you know if I configure something wrong? Any help appreciated!!

**Comment by Twizzledrizzle** [comment] 2016-05-30 08:24
Note, posted here becuase I got the same error message when I noticed I had to change to pythonw.exe!

**Comment by Twizzledrizzle** [comment] 2016-05-30 08:50
My Anaconda package had been corrupted... Sorry about reopening this. Anyway it works now, and I deleted my previous posts

**Comment by Yokan-Jan** [comment] 2016-12-20 03:04
Can I use it for the version of Python25?

**Comment by DamnWidget** [comment] 2016-12-20 09:01
The minimum python version supported by anaconda is Python 2.6 @Yokan-Jan I don't believe it works at all with Python 2.5

**Comment by purplezippo** [comment] 2017-01-13 05:28
I came across the same ploblem and by trying the following steps both the Anaconda2 and Anaconda3 could be installed smoothly, but only Anaconda3 worked, and I don't know why.
(1) clear the system path;
(2) start installer in admin;
(3) set the installation directory under root directory.
