### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by logileifs** [DamnWidget/anaconda#691] opened 2017-08-15 21:25 UTC
## Expected Behaviour
not use up 70% or more of RAM

## Actual Behaviour
using 70% or more of RAM

## Steps to Reproduce
Start sublime, keep it running for a while and jsonserver.py starts eating up memory
![anaconda_memoryleak](https://user-images.githubusercontent.com/2317815/29337386-96de3670-8200-11e7-8767-62ee9a6c1862.png)

## ST3, Anaconda and OS versions
ST3 build 3126
Ubuntu 14.04 
Anaconda v 2.1.20

## Anaconda's JsonServer Logs
**Note**: Anaconda's JsonServer logs can be found in:
* Linux: ~/.local/share/anaconda/logs
* OS X: ~/Library/Logs/anaconda
* Windows: %APPDATA\\Anaconda\\Logs

**Comment by DamnWidget** [comment] 2017-08-15 21:27
Thanks for your report but we are gonna need a bit more of information in order to even start looking into a "possible memory leak" just using the title of this issue...

Can you please follow the template and provide the required information?
Thank You.

**Comment by logileifs** [comment] 2017-08-15 21:37
[anaconda_jsonserver.log.zip](https://github.com/DamnWidget/anaconda/files/1226515/anaconda_jsonserver.log.zip)
[screenkey2.zip](https://github.com/DamnWidget/anaconda/files/1226517/screenkey2.zip)

**Comment by jamesandres** [comment] 2017-08-16 08:29
I am experiencing this too. It started happening sometime in the last 3 to 4 weeks. In my case the issue is usually accompanied by jsonserver using 100% cpu on one core of my machine (non-stop, I've seen it run that way for over 30 minutes until I `kill -9`'ed it).

If it happens again I'll try to capture some info for you.

**Comment by DamnWidget** [comment] 2017-08-16 09:24
Hi guys,
That is probably caused by a Jedi library update I need to know if you are using Python2 or Python3 as your configured anaconda interpreter. By the way, I've been testing a branch with a new update to Jedi tat seems to solve the problems in the previous update, I did not had any problem so far so I will probably push that into our next version today or tomorrow.

I will give you a ping so you can update and test it.

**Comment by laythun** [comment] 2017-08-16 10:38
I am having the same issue, and using Python

**Comment by tjphopkins** [comment] 2017-08-16 10:41
I am having the same issue, using Python 2

**Comment by jamesandres** [comment] 2017-08-16 10:42
I'm using python 2.7.13. At least I assume I am, because that's the default python in my bash/zsh `$PATH`. I haven't configured Anaconda to use anything different.

**Comment by DamnWidget** [comment] 2017-08-18 08:31
I released new version v2.1.21, let me know if yo still experience problems with it

**Comment by KM4YRI** [comment] 2017-08-18 16:22
@DamnWidget, just wanted to stop by and say thank you for fixing this issue so quick.  I got to work this morning to find that my machine had ran out of memory and crashed a few open programs.  Was headed here to file a bug report and just saw the upgrade message in Sublime Text.

I've already gotten a crash within the IDE since the upgrade was applied, which might be related.  I'll comment here with steps to reproduce if I get any further issues.

**Comment by jamesandres** [comment] 2017-08-21 15:52
Thanks for the potential fix @DamnWidget, I'm giving it a try now. If the issue reappears I'll let you know.

**Comment by tjphopkins** [comment] 2017-08-21 16:01
Thank you @DamnWidget for this fix.

**Comment by DamnWidget** [comment] 2017-08-22 07:36
This should be fixed, feel free to reopen again if needed.

**Closed by DamnWidget** 2017-08-22 07:36 UTC

**Comment by rogerlucas** [comment] 2019-03-16 17:21
Hello,
I have three open projects, working for more than 2 months without restarting the machine and look at the result (79Gb) very nice!

A test that can do to try to identify problem is to modify several files and save, at each operation the python process used by the anaconda module eats a piece of memory and does not release.

I do not know if it is standard, but here it is with auto formatting / indentation. So for example, your I leave several blank lines between two functions, when I save those extra lines are demoted. This is a case where I notice that the process memory increases and does not release.

<img width="988" alt="Screen Shot 2019-03-15 at 15 28 42" src="https://user-images.githubusercontent.com/527641/54478933-a65ab480-47f6-11e9-834e-6582112b15b2.png">
