### ISSUE TITLE
combine pep8, pyflakes and mmcabe using flake8 + support flake8 config files

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [DamnWidget/anaconda#274] opened 2015-02-17 21:20 UTC
flake8 combines the tools pep8, pyflakes and mccabe + supports project specific configuration via setup.cfg or tox.ini

it also supports the noqa marker for all tools not just one

**Comment by DamnWidget** [comment] 2015-02-19 12:37
I don't think add another layer in the top of the PyFlakes, PEP8 and McCabe libraries is helpful in any way. Anaconda already provides a wrapper around all those libraries using an architecture based in components that allows us to replace one of them by other thing in any moment with minimal or no impact at all in the rest of the plugin.

Flake8 is just a convenience that I don't see that convenient for us. Anaconda already supports per-project configuration (trough <project_name>.sublime-project files), by the way, PEP8 and PEP257 libraries also supports configuration using `setup.cfg`, `tox.ini` and `.pep8` or `.pep257` (respectively) per-project configuration if the file is present in the path.

A part from that, the required changes to support flake8 into the current Anaconda stack is huge so no real advantage/convenience here.

Add the noqa marker for other linters is just trivial, we already added some in the past (like for example in [here](https://github.com/DamnWidget/anaconda/blob/424588d30b63b0cfb4f5ee728285130eb469419a/anaconda_lib/import_validator.py#L40))

I don't think we are gonna support flake8 into the plugin as it's doesn't really offer anything *great* that make it really *worth*

**Comment by RonnyPfannschmidt** [comment] 2015-02-19 12:47
well, the project default configuration thats used in ci is tracked in the scm in tox.ini, the sublime configuration is not

other issues about noqa markers where closed as wontfix

**Comment by DamnWidget** [comment] 2015-02-19 12:57
Hi.
As I already said, you can use tox.ini files to configure the pep8 and pep257 behaviors. I am not sure now about PyFlakes and McCabe but I think that they support some sort of configuration via configuration files in some way.

About the other issues that you made reference, it is only one issue and it was marked as wontfix because the new auto-import feature was gonna make the noqa in unused imports just obsolete. Unfortunately the new auto-import support is delayed mainly because the library that we were gonna use is non stable and need proper fixes to can be even considered to be included into anaconda itself.

Feel free to open the #142 issue so we can discuss there adding noqa marker support for other parts of the linting reviewing specific scenarios or use cases.

**Comment by RonnyPfannschmidt** [comment] 2015-02-19 13:11
those tools don't use the same section as flake8

are you open to accept a PR implementing flake8 usage?

**Comment by DamnWidget** [comment] 2015-02-19 13:38
What you mean with "same section as flake8"?

I will accept PR always that flake8 is an alternative implementation to the current stack and can be enabled or disabled in the configuration (and of course it supports that exact same features, options and flexibility than the current solution).

**Comment by RonnyPfannschmidt** [comment] 2015-02-19 19:35
flake8 uses a certain config section in tox.ini/setup.cfg where one can excerpt control over all code analysis tools it involves at once

**Comment by DamnWidget** [comment] 2015-02-19 21:28
Hi @RonnyPfannschmidt 

I think is possible that you can implement something like that flake8 init files in really easy way for anaconda itself as anaconda already support global PATH configuration files (but only allow to override python_interpreter and extra_paths by design).

Take a look at [Environment hook files
](http://damnwidget.github.io/anaconda/anaconda_settings/#toc_7) section in the AnacondaST3 documentation web site

**Comment by RonnyPfannschmidt** [comment] 2015-02-19 22:05
randomly going offtopic - im starting to wonder if anaconda could be modified to run tox envs for stuff like code checks, unit-tests or even builds, in general (the tox envs is what we use on CI anyway - a tight integration seems sensible

**Comment by assumptionsoup** [comment] 2015-03-19 01:19
Flake8 [adds error codes to pyflakes](http://flake8.readthedocs.org/en/2.3.0/warnings.html).  This is what allows SublimeLinter-flake8 to consistently [theme errors/warnings](https://github.com/SublimeLinter/SublimeLinter-flake8/blob/d1c7f09fe9c5215cd6e1fab9167e1dd8f3d22c34/linter.py#L47) from all linters.  I don't care about flake8 so much as I care about being able to theme each linter error to my liking - which just so happens to be exactly what is in SublimeLinter-flake8.  +1 for Flake8 since it gets me closer to being able to do this.

**Comment by DamnWidget** [comment] 2015-03-19 10:11
Add a system to re-organize how anaconda treat the severity of different errors from different linters should be a non trivial task but not a hard one.

As always PRs are welcome.

**Comment by RonnyPfannschmidt** [comment] 2015-03-23 15:55
as part of a perf experiment i killed all my sublime plugins and restarted with just the sublime-linter one and sublime-jedi, since that setup served me well i haven't touched anaconda in a while,

as things are i no longer have a own motivation to provide the code

**Comment by DamnWidget** [comment] 2015-03-23 16:15
Then I suggest to @assumptionsoup to move his/her request to a new issue as I am closing this one now.

**Closed by DamnWidget** 2015-03-23 16:15 UTC
