### ISSUE TITLE
URL in docstring causes crash on auto-completion

### ISSUE THREAD

**Issue by jongiddy** [DamnWidget/anaconda#419] opened 2016-01-12 09:29 UTC
I have the following Python code in SublimeText build 3083 with Anaconda 1.4.17:
```
def significant_digits(x, n):
    """
    Round a float to a number of significant digits
    http://stackoverflow.com/questions/3410976/how-to-round-a-number-to-significant-figures-in-python
    """
```

SublimeText exits under any of the following:
1. I add or delete characters from the function name `significant_digits`;
2. In a separate file, I type `from sigdif import sign` and then TAB to autocomplete;
3. In a separate file, I type `from sigdif import significant_digits` (without autocompleting).

Disabling the Anaconda package stops the crashing.

I can change the function name to something else while Anaconda is disabled, but the problem re-occurs when Anaconda is re-enabled. (The function name is not important).

Deleting any of the docstring lines prevents the problem from occurring.

**Comment by DamnWidget** [comment] 2016-01-12 09:45
Can't reproduce it.
![419](https://cloud.githubusercontent.com/assets/329766/12259991/2b8fe7a6-b911-11e5-8898-49097f333563.png)

Probably there is something else in your system that produces that behaviour.

**Comment by jongiddy** [comment] 2016-01-13 15:54
It appears that a C++ dependency of Sublime somehow doesn't like the response:
```
About push back to ST3: {"doc": "sigdif.significnt_digits\nsignificnt_digits(x, n)<br><br>Round a float to a number of significant digits<br>http://stackoverflow.com/questions/3410976/how-to-round-a-number-to-significant-figures-in-python", "uid": "84d1899f55df4a51b9e5f72722bef60a", "success": true}

terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_range_insert
Aborted (core dumped)
```

With no symbols in the binary, it's hard to make out what exactly is failing.

For the record, this is on Ubuntu 14.04.

**Comment by DamnWidget** [comment] 2016-01-13 16:23
Well, is hard to me to give you an answer about a possible bug in the
Sublime Text 3 C++ code itself, and even harder taking into account that I
am not able to reproduce that behavior

On 13 January 2016 at 15:54, jongiddy <notifications@github.com> wrote:

> It appears that a C++ dependency of Sublime somehow doesn't like the
> response:
>
> About push back to ST3: {"doc": "sigdif.significnt_digits\nsignificnt_digits(x, n)<br><br>Round a float to a number of significant digits<br>http://stackoverflow.com/questions/3410976/how-to-round-a-number-to-significant-figures-in-python", "uid": "84d1899f55df4a51b9e5f72722bef60a", "success": true}
>
> terminate called after throwing an instance of 'std::length_error'
>   what():  vector::_M_range_insert
> Aborted (core dumped)
>
> With no symbols in the binary, it's hard to make out what exactly is
> failing.
>
> For the record, this is on Ubuntu 14.04.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DamnWidget/anaconda/issues/419#issuecomment-171340454>
> .
>



-- 
Join the Free Software Foundation and become Free as in Freedom

**Comment by DamnWidget** [comment] 2016-05-11 20:19
Any updates here @jongiddy ?

**Comment by jongiddy** [comment] 2016-05-14 05:38
Upgrading to ST build 3114 with Anaconda 1.4.26 seems to have fixed it. It was definitely still happening in build 3103, so seems to be fixed by the changes in this build.

**Comment by DamnWidget** [comment] 2016-05-14 10:50
Probably related with the crash in tooltips that they fixed as well. Closing this for now, open it again if you have to in the future

**Closed by DamnWidget** 2016-05-14 10:50 UTC
Labels: no replicable, unconfirmed

**Comment by jongiddy** [comment] 2016-05-15 12:36
Thanks for checking back on this issue's status. Although it wasn't a common error, it's good to know it won't strike randomly in the future.
